 name: MoneyDrops
 version: 0.0.1
 description: A simple plugin for adding money drops to entities and players
 author: CaptainInflamo
 website: https://github.com/TheStilbruch/MoneyDrops
 depend: ["Vault"]
 
 main: com.stilbruch.moneydrops.MoneyDropsPlugin